# Generated by Django 2.2.2 on 2019-11-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Название QR кода')),
                ('qr_city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('qr_campaign', models.CharField(blank=True, max_length=100, verbose_name='Campaign')),
                ('qr_source', models.CharField(blank=True, max_length=100, verbose_name='Source')),
                ('qr_product', models.CharField(blank=True, max_length=100, verbose_name='Product')),
                ('slug', models.SlugField(max_length=600, verbose_name='слаг')),
            ],
        ),
    ]
