# Generated by Django 2.2.2 on 2019-11-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='qr_quantity',
            field=models.IntegerField(blank=True, default=0, verbose_name='счетчик'),
        ),
    ]
