# Generated by Django 2.2.2 on 2019-11-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_list', '0003_list_qr_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='qr_date',
            field=models.DateTimeField(db_index=True, verbose_name='дата создания'),
        ),
    ]
