# Generated by Django 2.2.2 on 2019-11-22 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_list', '0005_auto_20191122_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ('-qr_date',)},
        ),
    ]
